import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Background, PageWrapper } from "@/components/layout";
import { ThemeProvider } from "@/components/providers";
import { ThemeToggle } from "@/components/common";
import { MenuBar } from "@/components/features/menu-bar";
import { Avatar } from "@/components/ui/avatar";
import { TopBar } from "@/components/layout/TopBar";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Background />
          <PageWrapper>
            <TopBar avatarTitle="Ł" avatarText="lukasz.dev" />
            {children}
          </PageWrapper>
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
