import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import { Background, PageWrapper } from "@/components/layout";
import { ThemeProvider, LenisProvider } from "@/components/providers";
import { ThemeToggle, KeyboardNav } from "@/components/common";
import { MenuBar } from "@/components/features/menu-bar";
import { Avatar } from "@/components/ui/avatar";
import { TopBar } from "@/components/layout/TopBar";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className={inter.variable} suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider>
            <LenisProvider>
              <Background />
              <PageWrapper>
                <TopBar avatarTitle="Ł" avatarText="lukasz.dev" />
                <div className="w-full flex-1" style={{ viewTransitionName: "page-content" }}>
                  {children}
                </div>
              </PageWrapper>
              <ThemeToggle />
              <KeyboardNav />
            </LenisProvider>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
