import { Project } from "./ProjectCard";

export const projects: Project[] = [
  {
    id: "1",
    title: "PantryPilot",
    description:
      "A modern kitchen companion app for managing your pantry, recipes, and shopping lists.",
    longDescription:
      "Track your pantry, import recipes with AI, and discover what you can cook with ingredients you already have. Features step-by-step cooking mode, automatic pantry updates, and smart shopping lists.",
    image: "/projects/pantrypilot.png",
    gradient: "bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700",
    tech: [
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Convex",
      "Clerk",
      "TanStack Start",
    ],
    liveUrl: "https://pantrypilot.szczesny.dev/",
    githubUrl: "https://github.com/lukasz-sz96/pantrypilot",
    featured: true,
    year: "2026",
    category: "Web Application",
    demoCredentials: {
      email: "demo@pantrypilot.app",
      password: "demopantry",
    },
  },
  // {
  //   id: "2",
  //   title: "Title",
  //   description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.",
  //   image: "https://placehold.co/800x600/2d1b4e/ffffff.png",
  //   gradient: "bg-gradient-to-br from-amber-500 via-orange-500 to-red-600",
  //   tech: ["React.js", "Tailwind", "Redux"],
  //   liveUrl: "#",
  //   githubUrl: "#",
  //   year: "2025",
  //   category: "Web Application",
  // },
  // {
  //   id: "3",
  //   title: "Title",
  //   description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
  //   image: "https://placehold.co/800x600/0d3b3b/ffffff.png",
  //   gradient: "bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-600",
  //   tech: ["React.js", "Tailwind", "Redux"],
  //   githubUrl: "#",
  //   year: "2025",
  //   category: "Web Application",
  // },
  // {
  //   id: "4",
  //   title: "Title",
  //   description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.",
  //   image: "https://placehold.co/800x600/3d1a3d/ffffff.png",
  //   gradient: "bg-gradient-to-br from-rose-500 via-pink-500 to-fuchsia-600",
  //   tech: ["React.js", "Tailwind", "Redux"],
  //   githubUrl: "#",
  //   year: "2025",
  //   category: "Web Application",
  // },
  // {
  //   id: "5",
  //   title: "Title",
  //   description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.",
  //   image: "https://placehold.co/800x600/1a2d4d/ffffff.png",
  //   gradient: "bg-gradient-to-br from-sky-500 via-blue-500 to-indigo-600",
  //   tech: ["React.js", "Tailwind", "Redux"],
  //   githubUrl: "#",
  //   year: "2025",
  //   category: "Web Application",
  // },
  // {
  //   id: "6",
  //   title: "Title",
  //   description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  //   image: "https://placehold.co/800x600/1f1f1f/888888.png",
  //   gradient: "bg-gradient-to-br from-slate-600 via-gray-700 to-zinc-800",
  //   tech: ["React.js", "Tailwind", "Redux"],
  //   githubUrl: "#",
  //   year: "2025",
  //   category: "Web Application",
  // },
];
