import { Project } from "./ProjectCard"

export const projects: Project[] = [
  {
    id: "1",
    title: "Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    image: "https://placehold.co/1200x800/1a1a2e/ffffff.png",
    gradient: "bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-700",
    tech: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Next.js", "Prisma"],
    liveUrl: "#",
    githubUrl: "#",
    featured: true,
    year: "2025",
    category: "Web Application",
  },
  {
    id: "2",
    title: "Title",
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.",
    image: "https://placehold.co/800x600/2d1b4e/ffffff.png",
    gradient: "bg-gradient-to-br from-amber-500 via-orange-500 to-red-600",
    tech: ["React.js", "Tailwind", "Redux"],
    liveUrl: "#",
    githubUrl: "#",
    year: "2025",
    category: "Web Application",
  },
  {
    id: "3",
    title: "Title",
    description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
    image: "https://placehold.co/800x600/0d3b3b/ffffff.png",
    gradient: "bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-600",
    tech: ["React.js", "Tailwind", "Redux"],
    githubUrl: "#",
    year: "2025",
    category: "Web Application",
  },
  {
    id: "4",
    title: "Title",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.",
    image: "https://placehold.co/800x600/3d1a3d/ffffff.png",
    gradient: "bg-gradient-to-br from-rose-500 via-pink-500 to-fuchsia-600",
    tech: ["React.js", "Tailwind", "Redux"],
    githubUrl: "#",
    year: "2025",
    category: "Web Application",
  },
  {
    id: "5",
    title: "Title",
    description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.",
    image: "https://placehold.co/800x600/1a2d4d/ffffff.png",
    gradient: "bg-gradient-to-br from-sky-500 via-blue-500 to-indigo-600",
    tech: ["React.js", "Tailwind", "Redux"],
    githubUrl: "#",
    year: "2025",
    category: "Web Application",
  },
  {
    id: "6",
    title: "Title",
    description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
    image: "https://placehold.co/800x600/1f1f1f/888888.png",
    gradient: "bg-gradient-to-br from-slate-600 via-gray-700 to-zinc-800",
    tech: ["React.js", "Tailwind", "Redux"],
    githubUrl: "#",
    year: "2025",
    category: "Web Application",
  },
]
